# Generated by Django 4.2.16 on 2024-11-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Project',
        ),
    ]
